### ISSUE TITLE
faster Neus

### ISSUE THREAD

**Issue by fefespn** [byeongjun-park/HarmonyView#1]
Hey, Thanks for your work !
I asked the same in the SyncDreamer repo,
Are you planning to add faster neus implementations ? like neus2 or something else ?

**Comment by byeongjun-park** [comment]
Hi, thank you for the intriguing suggestion!! 
I also think "faster NeuS (e.g., NeuS2)" would be helpful for other future studies. 
I'll work on this after I get back from holiday.

**Comment by fefespn** [comment]
Ok thanks.
Maybe I can also look at it in the next couple of days maybe I can help.
Happy new year.
