### ISSUE TITLE
3d Reconstruction

### ISSUE THREAD

**Issue by adeerAI** [byeongjun-park/HarmonyView#3]
Has anyone been able to come up with a colab notebook for 3d reconstruction, I am facing problems in the conflicting libraries, still trying my best, but if anyone has been able to achieve this let me know. Thanks. I am facing this problem mainly, It does not install properly.
#!pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

**Comment by byeongjun-park** [comment]
Does setting the GCC/G++ version to 8 or higher cause the same problem?

**Comment by adeerAI** [comment]
I tried with Colab but it didn't work, then I tried on a local workstation, installed all the libraries but still failed. So I just gave up.

**Comment by byeongjun-park** [comment]
Please feel free to open a new issue if you have any other questions or concerns.
