### ISSUE TITLE
How to generate the 3Dmesh and NeRF from this repo?

### ISSUE THREAD

**Issue by SaShukla090** [byeongjun-park/HarmonyView#5]
I visited your HF spaces, and you mentioned that we can generate NeRF or 3D mesh using this repo.  But I am not sure how to do it. Could you please give detailed information for the reconstructing the NeRF and 3D mesh using your code?

**Comment by byeongjun-park** [comment]
Hi, thanks for your interest in our work.

If you have a multiview image from HF, you just run the "train_renderer.py" as below.

**python train_renderer.py -i /path/to/your/image.png -n neus -b configs/neus.yaml -l /output/folder/to/output**

Make sure to replace /path/to/your/image.png with the actual path to the image downloaded from HF. Additionally, replace /output/folder/to/output with the desired output folder path.

If you encounter any issues or have further questions, feel free to ask!
