### ISSUE TITLE
Problem about inference

### ISSUE THREAD

**Issue by YuyangYin** [byeongjun-park/HarmonyView#7]
hi,nice work. When I try to generate my own image, the bug is as follows. My input image is rgba form. Is there any fault in my config? thx.

CUDA_VISIBLE_DEVICES="3" python generate.py  --cfg_scales 2 1 --decomposed_sampling                    --input /data/users/yyy/4dgen_exp_pl/4dgen_exp/data/mario_rgba_pose0/0.png                    --output /data/users/yyy/4dgen_exp_pl/4dgen_exp/exp_data/ham_output                    --cfg_scale 2.0                    --elevation 30                    --crop_size 200
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Selected timesteps for ddim sampler: [  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146 151 156 161 166 171 176
 181 186 191 196 201 206 211 216 221 226 231 236 241 246 251 256 261 266
 271 276 281 286 291 296 301 306 311 316 321 326 331 336 341 346 351 356
 361 366 371 376 381 386 391 396 401 406 411 416 421 426 431 436 441 446
 451 456 461 466 471 476 481 486 491 496 501 506 511 516 521 526 531 536
 541 546 551 556 561 566 571 576 581 586 591 596 601 606 611 616 621 626
 631 636 641 646 651 656 661 666 671 676 681 686 691 696 701 706 711 716
 721 726 731 736 741 746 751 756 761 766 771 776 781 786 791 796 801 806
 811 816 821 826 831 836 841 846 851 856 861 866 871 876 881 886 891 896
 901 906 911 916 921 926 931 936 941 946 951 956 961 966 971 976 981 986
 991 996]
loading model from ckpt/ckpt/syncdreamer-pretrain.ckpt ...
Selected timesteps for ddim sampler: [  1  21  41  61  81 101 121 141 161 181 201 221 241 261 281 301 321 341
 361 381 401 421 441 461 481 501 521 541 561 581 601 621 641 661 681 701
 721 741 761 781 801 821 841 861 881 901 921 941 961 981]
Decomposed Guidance (DG) Sampling
unconditional scales [2.0]
DDIM Sampler:   0%|                                                                                                                                                                                           | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/users/yyy/HarmonyView/generate.py", line 93, in <module>
    main()
  File "/data/users/yyy/HarmonyView/generate.py", line 68, in main
    x_sample = model.sample(sampler, data, flags.cfg_scales)
  File "/data/users/yyy/HarmonyView/ldm/models/diffusion/sync_dreamer.py", line 495, in sample
    x_sample, inter = sampler.sample(input_info, clip_embed, unconditional_scale=cfg_scale, log_every_t=inter_interval)
  File "/home/yyy/anaconda3/envs/yyy/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/yyy/HarmonyView/ldm/models/diffusion/sync_dreamer.py", line 675, in sample
    x_target_noisy = self.denoise_apply(x_target_noisy, input_info, clip_embed, time_steps, index, unconditional_scale, is_step0=index==0)
  File "/home/yyy/anaconda3/envs/yyy/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/users/yyy/HarmonyView/ldm/models/diffusion/sync_dreamer.py", line 644, in denoise_apply
    noise = self.model.model.predict_with_decomposed_unconditional_scales(x_target_noisy_, time_steps_, clip_embed_, volume_feats_, x_concat_, unconditional_scale)
  File "/data/users/yyy/HarmonyView/ldm/models/diffusion/sync_dreamer.py", line 139, in predict_with_decomposed_unconditional_scales
    s = s + unconditional_scales[0] * (s - s_uc1) + unconditional_scales[1] * (s - s_uc2)
IndexError: list index out of range

**Comment by byeongjun-park** [comment]
Hi, thank you for your interest in our work.

When I looked at your command line, there exists "--cfg_scale 2.0" which is not our arg parameter.

On a related note, I see the following output in your terminal, and maybe flags.cfg_scale is used in the sampling process.

""
Decomposed Guidance (DG) Sampling
unconditional scales [2.0]
""

There seem to be a few modifications in your code, but please note that flags.cfg_scales should be used in the sampling process.

**Comment by YuyangYin** [comment]
o, it works. Thanks.  Another question. If the input image elevation is 0, the output image elevation is 30? In syncdreamer, I think the setting is that.

**Comment by YuyangYin** [comment]
And crop_size equals -1 or 200? which is better?

**Comment by YuyangYin** [comment]
I find the output is two concatenated images. In code https://github.com/byeongjun-park/HarmonyView/blob/main/generate.py#L78, the output number is equal to B. B is 2. My question is what is the difference between them? Which result should I use?  Thanks a lot.

**Comment by byeongjun-park** [comment]
1. Yes, the generated images' elevation is fixed to 30 (same as SyncDreamer).
2. In the evaluation, we set crop_size=-1, but you should set an appropriate crop_size (e.g., 200) to get a better result.
3. Each multiview image is generated from different random noises, so you can use anything.

**Comment by YuyangYin** [comment]
My gpu memory is 24G. I find the memory use about HaromonyView is unstable. Normarlly, it needs 20-22G. But for some cases, the memory is larger than it. Although my input image resolution and conifg are same. So out of memory promblem occurs. I follow syncdreamer insturction and set sample_num=1. I think the memory use is half of the origin, but it is same. So how can I decrease the memory use about HaromonyView? Thanks!

**Comment by YuyangYin** [comment]
The problem meets when I test multi images, like:
for i in range(16):
     read_image(i)
     main(HaromonyView)

The out of memory problem occurs in i=2. I think the gpu memory is not released before?

**Comment by YuyangYin** [comment]
I think it is not problem in your code. I can inference only one image every time. Thanks.

**Comment by YuyangYin** [comment]
I am the author of 4DGen(https://vita-group.github.io/4DGen/). I would like to inquire about the possibility of sharing the images used in your paper. I am interested in experimenting with these images using the image-to-4d technique. If the results turn out to be impressive, it could be a great opportunity for mutual promotion.  Only need front view image(elevation=0) as input.

Thank you very much for considering and for your support.

**Comment by YuyangYin** [comment]
I'm the author of 4DGen(https://vita-group.github.io/4DGen/). I would like to inquire about the possibility of sharing the images used in your paper. I am interested in experimenting with these images using the image-to-4d technique. If the results turn out to be impressive, it could be a great opportunity for mutual promotion. Only origin inputs of front view(evation=0) are needed. 

Thank you very much for considering and for your support.

**Comment by byeongjun-park** [comment]
Thanks for the kind words. We already shared the images used in our paper, and you can find them in the "harmonyview_testset" folder. Please feel free to use these images for your projects.

**Comment by YuyangYin** [comment]
Thanks！
